[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
spl_payment = "ADJTuM8BMjCupygz4jWP8GPhh3p4cfveYs5h7mfCDw1Y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/flynn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
