[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_payment = "4AdtuALwCGgQs9o3L3Hb541TYpcMjNJFoAbz544cCHra"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/flynn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
